package repository

import (
	"context"
	"sort"
	"strings"

	"github.com/tangwy-t/UniCenter/uni_core/internal/model/dto/request"
	"github.com/tangwy-t/UniCenter/uni_core/internal/model/entity"

	"gorm.io/gorm"
)

type RoleRepo struct {
	db *gorm.DB
}

// NewRoleRepository returns a RoleRepository backed by the given *gorm.DB.
// Snowflake IDs for association records (SysRoleMenu, SysRoleDept) are
// generated by the GORM BeforeCreate callback (database.RegisterIDCallback).
func NewRoleRepository(db *gorm.DB) *RoleRepo {
	return &RoleRepo{db: db}
}

func (r *RoleRepo) applyRoleFilters(db *gorm.DB, query *request.RoleQuery) *gorm.DB {
	if query.Name != "" {
		db = db.Where("name LIKE ?", "%"+query.Name+"%")
	}
	if query.Code != "" {
		db = db.Where("code LIKE ?", "%"+query.Code+"%")
	}
	if query.Status != nil {
		db = db.Where("status = ?", *query.Status)
	}
	return db
}

func (r *RoleRepo) FindPage(ctx context.Context, query *request.RoleQuery) ([]entity.SysRole, int64, error) {
	countDB := r.applyRoleFilters(r.db.WithContext(ctx).Model(&entity.SysRole{}), query)
	dataDB := r.applyRoleFilters(r.db.WithContext(ctx).Model(&entity.SysRole{}), query).Order("sort ASC, id ASC")
	return paginate[entity.SysRole](countDB, dataDB, query)
}

// FindExistingIDs returns the subset of ids that exist in sys_role.
// Used by the service layer to validate roleIDs before an Association write
// (which would otherwise upsert a phantom role for an unknown ID).
func (r *RoleRepo) FindExistingIDs(ctx context.Context, ids []uint64) ([]uint64, error) {
	if len(ids) == 0 {
		return nil, nil
	}
	var existing []uint64
	err := r.db.WithContext(ctx).Model(&entity.SysRole{}).
		Where("id IN ?", ids).Pluck("id", &existing).Error
	return existing, err
}

// FindExistingMenuIDs returns the subset of menuIDs that exist in sys_menu.
// Used by the service layer to validate menuIDs before an Association write.
func (r *RoleRepo) FindExistingMenuIDs(ctx context.Context, ids []uint64) ([]uint64, error) {
	if len(ids) == 0 {
		return nil, nil
	}
	var existing []uint64
	err := r.db.WithContext(ctx).Model(&entity.SysMenu{}).
		Where("id IN ?", ids).Pluck("id", &existing).Error
	return existing, err
}

// FindExistingDeptIDs returns the subset of deptIDs that exist in sys_dept.
// Used by the service layer to validate deptIDs before an Association write.
func (r *RoleRepo) FindExistingDeptIDs(ctx context.Context, ids []uint64) ([]uint64, error) {
	if len(ids) == 0 {
		return nil, nil
	}
	var existing []uint64
	err := r.db.WithContext(ctx).Model(&entity.SysDept{}).
		Where("id IN ?", ids).Pluck("id", &existing).Error
	return existing, err
}

func (r *RoleRepo) FindAll(ctx context.Context) ([]entity.SysRole, error) {
	var roles []entity.SysRole
	err := r.db.WithContext(ctx).Order("sort ASC, id ASC").Find(&roles).Error
	return roles, err
}

func (r *RoleRepo) FindByID(ctx context.Context, id uint64) (*entity.SysRole, error) {
	var role entity.SysRole
	err := r.db.WithContext(ctx).Preload("Menus").Preload("Depts").First(&role, id).Error
	if err != nil {
		return nil, err
	}
	return &role, nil
}

func (r *RoleRepo) CreateWithAssociations(ctx context.Context, role *entity.SysRole, menuIDs, deptIDs []uint64) error {
	return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		if err := tx.Create(role).Error; err != nil {
			return err
		}
		if err := r.replaceRoleMenus(tx, role.ID, menuIDs); err != nil {
			return err
		}
		if err := r.replaceRoleDepts(tx, role.ID, deptIDs); err != nil {
			return err
		}
		return nil
	})
}

// UpdateWithAssociationsAndUserIDs updates the role and its associations
// and returns the IDs of users currently assigned to the role, all within a single
// transaction. This eliminates the race window between querying user IDs and committing
// the update — the caller can invalidate the permission cache for every user that was
// assigned at the moment the transaction ran.
func (r *RoleRepo) UpdateWithAssociationsAndUserIDs(ctx context.Context, role *entity.SysRole, menuIDs, deptIDs []uint64) ([]uint64, error) {
	var userIDs []uint64
	err := r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		if err := tx.WithContext(ctx).Table("sys_user_role").
			Where("role_id = ?", role.ID).
			Pluck("user_id", &userIDs).Error; err != nil {
			return err
		}
		return r.updateWithAssociationsInTx(ctx, tx, role, menuIDs, deptIDs)
	})
	return userIDs, err
}

func (r *RoleRepo) updateWithAssociationsInTx(ctx context.Context, tx *gorm.DB, role *entity.SysRole, menuIDs, deptIDs []uint64) error {
	if err := tx.WithContext(ctx).Model(role).Updates(role).Error; err != nil {
		return err
	}
	if err := r.replaceRoleMenus(tx, role.ID, menuIDs); err != nil {
		return err
	}
	if err := r.replaceRoleDepts(tx, role.ID, deptIDs); err != nil {
		return err
	}
	return nil
}

// replaceRoleMenus swaps a role's menu set via Association("Menus").Replace.
// SetupJoinTable gives the association the real SysRoleMenu schema so each
// join row gets a snowflake ID. The caller must have validated every menuID
// exists; an unknown ID would be upserted as a phantom menu.
func (r *RoleRepo) replaceRoleMenus(tx *gorm.DB, roleID uint64, menuIDs []uint64) error {
	menus := make([]entity.SysMenu, 0, len(menuIDs))
	for _, mid := range menuIDs {
		menus = append(menus, entity.SysMenu{BaseEntity: entity.BaseEntity{ID: mid}})
	}
	return tx.Model(&entity.SysRole{BaseEntity: entity.BaseEntity{ID: roleID}}).
		Association("Menus").Replace(menus)
}

// replaceRoleDepts swaps a role's dept set via Association("Depts").Replace.
// Same validation precondition as replaceRoleMenus.
func (r *RoleRepo) replaceRoleDepts(tx *gorm.DB, roleID uint64, deptIDs []uint64) error {
	depts := make([]entity.SysDept, 0, len(deptIDs))
	for _, did := range deptIDs {
		depts = append(depts, entity.SysDept{BaseEntity: entity.BaseEntity{ID: did}})
	}
	return tx.Model(&entity.SysRole{BaseEntity: entity.BaseEntity{ID: roleID}}).
		Association("Depts").Replace(depts)
}

func (r *RoleRepo) Delete(ctx context.Context, id uint64) error {
	return r.db.WithContext(ctx).Delete(&entity.SysRole{}, id).Error
}

// UpdateStatus updates only the status column — role status changes must go
// through the guarded service path (admin role is not toggleable).
func (r *RoleRepo) UpdateStatus(ctx context.Context, id uint64, status int8) error {
	return r.db.WithContext(ctx).Model(&entity.SysRole{}).Where("id = ?", id).
		Update("status", status).Error
}

// UpdateSort updates only the sort column. Unlike the full Update path
// (UpdateWithAssociationsAndUserIDs) it never touches menu/dept associations,
// so batch reordering from the list page is cheap and side-effect free.
func (r *RoleRepo) UpdateSort(ctx context.Context, id uint64, sort int) error {
	return r.db.WithContext(ctx).Model(&entity.SysRole{}).Where("id = ?", id).
		Update("sort", sort).Error
}

func (r *RoleRepo) DeleteWithAssociations(ctx context.Context, id uint64) error {
	return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		if err := r.DeleteRoleMenusTx(ctx, tx, id); err != nil {
			return err
		}
		if err := r.DeleteRoleDeptsTx(ctx, tx, id); err != nil {
			return err
		}
		if err := r.DeleteTx(ctx, tx, id); err != nil {
			return err
		}
		return nil
	})
}

func (r *RoleRepo) DeleteTx(ctx context.Context, tx *gorm.DB, id uint64) error {
	return tx.WithContext(ctx).Delete(&entity.SysRole{}, id).Error
}

func (r *RoleRepo) DeleteRoleMenusTx(ctx context.Context, tx *gorm.DB, roleID uint64) error {
	return tx.WithContext(ctx).Where("role_id = ?", roleID).Delete(&entity.SysRoleMenu{}).Error
}

func (r *RoleRepo) DeleteRoleDeptsTx(ctx context.Context, tx *gorm.DB, roleID uint64) error {
	return tx.WithContext(ctx).Where("role_id = ?", roleID).Delete(&entity.SysRoleDept{}).Error
}

func (r *RoleRepo) FindUserIDsByRoleID(ctx context.Context, roleID uint64) ([]uint64, error) {
	var userIDs []uint64
	err := r.db.WithContext(ctx).Table("sys_user_role").
		Where("role_id = ?", roleID).
		Pluck("user_id", &userIDs).Error
	return userIDs, err
}

// FindRoleIDsByPerm 反查持有指定权限码的角色集合（docker 事件通知的受众
// 收敛用，满足 dockernotify.RolePermQuery 的口径）。链路：sys_menu.perms
// （码挂在菜单/按钮上）→ sys_role_menu → 角色并集。
//
// SQL 拉取「perms 非空」的 (role_id, perms) 扁平行后在 Go 侧做码匹配，
// 两个「为什么」：
//   - perms 的**多值形态**：历史数据里 perms 可能是逗号分隔多码（本仓库的
//     种子都是单码，但字段语义不排除 CSV）。运行时权限检查按整串精确比对
//     （slices.Contains），CSV 行等于一个码都不授；受众口径取「按码拆开算」
//     —— 收敛的语义是「组织里谁该被通报」，比「谁能过运行时检查」宽半格
//     是有意的（通知侧宁误报不漏报）。CSV 匹配留在 Go 侧还因为它跨库：
//     FIND_IN_SET 绑死 MySQL，四段 LIKE 是晦涩的方言；RBAC 表规模小
//     （角色×菜单），全量行是几 KB 的事，不值一条方言 SQL。
//   - 与运行时权限解析**同口径**的不额外过滤：不按 sys_role.status /
//     菜单 status 过滤（auth 的 FindRoleMenuIDs 同样不看它们 —— 被停用的
//     角色在运行时照常授权，受众跟着同口径，不在这里发明第二套语义）；
//     菜单软删由 Model(&entity.SysMenu{}) 注入的软删条件兜住（与
//     FindMenuPerms 同款）。角色软删不显式过滤：角色删除走
//     DeleteWithAssociations（join 行硬删），该角色自然从结果消失。
//
// 结果去重升序：同一码挂多个菜单（docker:list 挂 4 个页面）时同一角色
// 会出多行，去重是本方法的契约；升序让缓存与 TargetIDs 的呈现稳定。
func (r *RoleRepo) FindRoleIDsByPerm(ctx context.Context, perm string) ([]uint64, error) {
	if perm == "" {
		return nil, nil
	}
	var rows []struct {
		RoleID uint64
		Perms  string
	}
	err := r.db.WithContext(ctx).Model(&entity.SysMenu{}).
		Joins("JOIN sys_role_menu ON sys_role_menu.menu_id = sys_menu.id").
		Where("sys_menu.perms IS NOT NULL AND sys_menu.perms != ''").
		Select("sys_role_menu.role_id AS role_id, sys_menu.perms AS perms").
		Scan(&rows).Error
	if err != nil {
		return nil, err
	}
	seen := make(map[uint64]struct{}, len(rows))
	ids := make([]uint64, 0, len(rows))
	for _, row := range rows {
		if !permCSVContains(row.Perms, perm) {
			continue
		}
		if _, dup := seen[row.RoleID]; dup {
			continue
		}
		seen[row.RoleID] = struct{}{}
		ids = append(ids, row.RoleID)
	}
	sort.Slice(ids, func(i, j int) bool { return ids[i] < ids[j] })
	return ids, nil
}

// permCSVContains 判断 perms 串（单码或逗号多码）是否含有 code：
// 按逗号拆开、trim 后**整词**比对 —— 子串不算命中（docker:listing 不得
// 顶替 docker:list），空白容错只是对人工录入形态的防御。
func permCSVContains(perms, code string) bool {
	for _, part := range strings.Split(perms, ",") {
		if strings.TrimSpace(part) == code {
			return true
		}
	}
	return false
}
